name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          
          # Üretilecek dosyalar burada belirtiliyor
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake-progress.svg

          # YENİ VE DOĞRU YÖNTEM: Tüm özelleştirmeler 'args' altında toplanır
          args: |
            --color_snake "#FFD700"
            --snake_tail_length 30
            --animation_duration 12
            --color_dots "#d6d6d6,#b8b8b8,#9a9a9a,#7c7c7c,#5e5e5e"

      - name: Push generated files to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
